Aplikacja/Models/IPaddr.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.Net;
using Microsoft.AspNetCore;


namespace Aplikacja.Models
{
    public class IPaddr
    {
        [Required(ErrorMessage = "Podaj adres w formie x.x.x.x")]
        [StringLength(15)]
        public string _IPaddrInput = "1.1.1.1";

        public string IPaddrInput
        {
            get
            { return _IPaddrInput; }
            set
            { _IPaddrInput = value; }
        }
        public string def { get; set; }

        /*public static string GetUserIPAddress()
        {
            var context = Request.Host.Value;//System.Web.HttpContext.Current;
            string ip = String.Empty;

            if (context.Request.ServerVariables["HTTP_X_FORWARDED_FOR"] != null)
                ip = context.Request.ServerVariables["HTTP_X_FORWARDED_FOR"].ToString();
            else if (!String.IsNullOrWhiteSpace(context.Request.UserHostAddress))
                ip = context.Request.UserHostAddress;

            if (ip == "::1")
                ip = "127.0.0.1";

            return ip;
        }*/
    }
}

Aplikacja/Models/IPinfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Aplikacja.Models
{
    public class IPinfo
    {
        public int ID { get; set; }
        public string IPAddress { get; set; }
        public string countryName { get; set; }
        public string countryCode { get; set; }
        public string regionName { get; set; }
        public string cityName { get; set; }
        public string zipCode { get; set; }
        public string timeZone { get; set; }
        public float longitude { get; set; }
        public float latitude { get; set; }
    }
}

Aplikacja/Models/IPinfo2.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Aplikacja.Models
{
    public class IPinfo2
    {
        public int ID { get; set; }
        public string IPAddress { get; set; }
        public string countryName { get; set; }
        public string countryCode { get; set; }
        public string regionName { get; set; }
        public string cityName { get; set; }
        public string zipCode { get; set; }
        public string timeZone { get; set; }
        public float longitude { get; set; }
        public float latitude { get; set; }
    }
}

Aplikacja/Controllers/IPaddrController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Aplikacja.Models;

namespace Aplikacja.Controllers
{
    public class IPaddrController : Controller
    {
        public IActionResult ValidateInput()
        {
            var ipaddr = new IPaddr();
            ipaddr.def = "def";
            ViewBag.def = Request.Host.Value;
            ipaddr._IPaddrInput = Request.Host.Host;
            //var i = View(new IPaddr());
            
            return View(ipaddr);
        }
       
        [HttpPost]
        public IActionResult ValidateInput(IPaddr ipaddr)
        {
            if (!ModelState.IsValid)
            {
                return View(ipaddr);
            }
            //string test = inputString;
            //IPaddr IPaddrInput = new IPaddr();
            //IPaddrInput.IPaddrInput = inputString;
            //System.Diagnostics.Debug.WriteLine("kaczucha_ipaddr" + ipaddr.IPaddrInput);

            return RedirectToAction("Execute", "TheLast", new { inputString = ipaddr.IPaddrInput });
            
        }
    }
}

Aplikacja/Views/IPaddr/IPinfo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Aplikacja.Models.IPinfo

@{
    <h2>Informacja o adresie IP:</h2>


    <table>
        <tr>
            <th>Country Name:</th> <td>@Html.DisplayFor(Model=>Model.countryName)</td>
        </tr>
        <tr>
            <th>Country Code:</th> <td>@Html.DisplayFor(Model => Model.countryCode)</td>
        </tr>
        <tr>
            <th>City Name:</th>
            <td>@Html.DisplayFor(Model => Model.cityName)</td>
        </tr>
        <tr>
            <th>Region Name:</th>
            <td>@Html.DisplayFor(Model => Model.regionName)</td>
        </tr>
        <tr>
            <th>Zip Code:</th>
            <td>@Html.DisplayFor(Model => Model.zipCode)</td>
        </tr>
        <tr>
            <th>Longitude:</th>
            <td>@Html.DisplayFor(Model => Model.longitude)</td>
        </tr>
        <tr>
            <th>Latitude:</th>
            <td>@Html.DisplayFor(Model => Model.latitude)</td>
        </tr>
        <tr>
            <th>Time zone:</th>
            <td>@Html.DisplayFor(Model => Model.timeZone)</td>
        </tr>



    </table>
}

Aplikacja/Views/IPaddr/IPinfo2.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Aplikacja.Models.IPinfo2

@{
    <h2>Informacja o adresie IP:</h2>


    <table>
        <tr>
            <th>Country Name:</th> <td>@Html.DisplayFor(Model=>Model.countryName)</td>
        </tr>
        <tr>
            <th>Country Code:</th> <td>@Html.DisplayFor(Model => Model.countryCode)</td>
        </tr>
        <tr>
            <th>City Name:</th>
            <td>@Html.DisplayFor(Model => Model.cityName)</td>
        </tr>
        <tr>
            <th>Region Name:</th>
            <td>@Html.DisplayFor(Model => Model.regionName)</td>
        </tr>
        <tr>
            <th>Zip Code:</th>
            <td>@Html.DisplayFor(Model => Model.zipCode)</td>
        </tr>
        <tr>
            <th>Longitude:</th>
            <td>@Html.DisplayFor(Model => Model.longitude)</td>
        </tr>
        <tr>
            <th>Latitude:</th>
            <td>@Html.DisplayFor(Model => Model.latitude)</td>
        </tr>
        <tr>
            <th>Time zone:</th>
            <td>@Html.DisplayFor(Model => Model.timeZone)</td>
        </tr>



    </table>
}

Aplikacja/Views/IPaddr/ValidateInput.cshtml
@model Aplikacja.Models.IPaddr


@{
    ViewData["Title"] = "IP Check";
}

<h2>Sprawdz dane o adresie IP</h2>
@*
@using (@Html.BeginForm("ValidateInput","IPaddr", FormMethod.Post, new { @id = "form1", @enctype = "multipart/form-data" }))
{
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <label id="lblDescription">IPaddrInput</label>
        @Html.TextAreaFor(m=>m.IPaddrInput, new {@id="txtDescription",@name="IPaddrInput" })
        @Html.ValidationMessageFor(m => m.IPaddrInput, "", new { @class = "text-danger" })

        <input type="submit" id="bttn_Submit" />
        }
    *@

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @ViewBag.def <br/>
            @Html.LabelFor(model => model.IPaddrInput, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.IPaddrInput, new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.def } })
                @Html.ValidationMessageFor(model => model.IPaddrInput, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sprawdz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>